name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    # Run tests if applicable
    - run: npm test

    # Build and start containers using docker-compose
    - run: docker-compose build
    - run: docker-compose up -d

    # Deploy to OnRender (add your OnRender-specific deploy step)
    - name: Deploy to OnRender
      env:
        ONRENDER_API_KEY: ${{ secrets.ONRENDER_API_KEY }}
      run: |
        curl -X POST https://api.onrender.com/deploys \
          -H "Authorization: Bearer $ONRENDER_API_KEY" \
          -F "app=Projet-Groupe11-Testing" \
          -F "branch=main" \
          -F "build_output_path=./build" \
          -F "docker=true"
