name: Node.js CI/CD with Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [22.x]

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install libssl1.1 (for mongodb-memory-server)
      run: |
        sudo apt-get update
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb


    - name: Install libssl1.1 (for MongoMemoryServer if needed)
      run: |
        sudo apt-get update
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb || true

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Run tests
      env:
        MONGO_URL: mongodb://admin:password@localhost:27017/test?authSource=admin
        NODE_ENV: test
      run: npm test -- --ci --coverage

    - name: Build container
      run: docker-compose build

    - name: Start container
      run: docker-compose up -d
